# Generated by Django 5.1.2 on 2024-10-30 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortenUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_url", models.URLField()),
                ("key", models.CharField(max_length=255, unique=True)),
                ("creator_ip", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "creator_user_agent",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="UrlStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visited_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shorten_url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shortenurl.shortenurl",
                    ),
                ),
            ],
        ),
    ]
